"""initial schema

Revision ID: 0b231dde9c97
Revises: 
Create Date: 2026-05-28 17:56:38.833660+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b231dde9c97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm_source_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_firm_id', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload_path', sa.String(length=1024), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('name_raw', sa.String(length=512), nullable=False),
    sa.Column('name_normalized', sa.String(length=512), nullable=True),
    sa.Column('website_raw', sa.String(length=1024), nullable=True),
    sa.Column('website_normalized', sa.String(length=512), nullable=True),
    sa.Column('phone_raw', sa.String(length=64), nullable=True),
    sa.Column('phone_normalized', sa.String(length=32), nullable=True),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.Column('attorney_count', sa.Integer(), nullable=True),
    sa.Column('source_last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contacts', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('offices', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('practice_areas_raw', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('practice_areas_matched', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('practice_areas_unmatched', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('additional_data', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_firm_id', name='uq_source_record_source_id'),
    sa.UniqueConstraint('source', 'source_url', name='uq_source_record_url')
    )
    with op.batch_alter_table('firm_source_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firm_source_records_name_normalized'), ['name_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_source_records_phone_normalized'), ['phone_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_source_records_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_source_records_website_normalized'), ['website_normalized'], unique=False)

    op.create_table('firms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('name_normalized', sa.String(length=512), nullable=True),
    sa.Column('website', sa.String(length=1024), nullable=True),
    sa.Column('website_normalized', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('phone_normalized', sa.String(length=32), nullable=True),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.Column('attorney_count', sa.Integer(), nullable=True),
    sa.Column('field_provenance', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('firms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firms_name_normalized'), ['name_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_firms_phone_normalized'), ['phone_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_firms_website_normalized'), ['website_normalized'], unique=False)

    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('phone_normalized', sa.String(length=32), nullable=True),
    sa.Column('bar_number', sa.String(length=64), nullable=True),
    sa.Column('bar_state', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_state', 'bar_number', name='uq_person_bar')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persons_bar_state'), ['bar_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_phone_normalized'), ['phone_normalized'], unique=False)

    op.create_table('practice_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['practice_areas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_areas_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_areas_slug'), ['slug'], unique=True)

    op.create_table('firm_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'person_id', 'start_date', name='uq_firm_person')
    )
    with op.batch_alter_table('firm_persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firm_persons_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_persons_person_id'), ['person_id'], unique=False)

    op.create_table('firm_practice_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('practice_area_id', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_area_id'], ['practice_areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['firm_source_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'practice_area_id', 'source_record_id', name='uq_firm_practice_area_source')
    )
    with op.batch_alter_table('firm_practice_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firm_practice_areas_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_practice_areas_practice_area_id'), ['practice_area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_practice_areas_source_record_id'), ['source_record_id'], unique=False)

    op.create_table('match_review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_record_a_id', sa.Integer(), nullable=False),
    sa.Column('source_record_b_id', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Float(), nullable=False),
    sa.Column('score_components', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('thresholds', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('reviewer', sa.String(length=64), nullable=True),
    sa.Column('reviewer_notes', sa.String(length=1024), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resulting_firm_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status in ('pending','approved','rejected','auto_approved')", name='ck_match_review_status'),
    sa.CheckConstraint('source_record_a_id < source_record_b_id', name='ck_match_review_ordered_pair'),
    sa.ForeignKeyConstraint(['resulting_firm_id'], ['firms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_record_a_id'], ['firm_source_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_b_id'], ['firm_source_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_review_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_review_queue_source_record_a_id'), ['source_record_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_review_queue_source_record_b_id'), ['source_record_b_id'], unique=False)

    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('is_headquarters', sa.Boolean(), nullable=False),
    sa.Column('street_raw', sa.String(length=512), nullable=True),
    sa.Column('street_normalized', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=8), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('phone_normalized', sa.String(length=32), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offices_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offices_phone_normalized'), ['phone_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_offices_state'), ['state'], unique=False)

    op.create_table('practice_area_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_area_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=256), nullable=False),
    sa.Column('alias_normalized', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['practice_area_id'], ['practice_areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_normalized', name='uq_alias_normalized')
    )
    with op.batch_alter_table('practice_area_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_area_aliases_alias_normalized'), ['alias_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_area_aliases_practice_area_id'), ['practice_area_id'], unique=False)

    op.create_table('unmatched_practice_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.String(length=512), nullable=False),
    sa.Column('normalized_value', sa.String(length=512), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sample_source_record_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sample_source_record_id'], ['firm_source_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_value', name='uq_unmatched_normalized')
    )
    with op.batch_alter_table('unmatched_practice_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unmatched_practice_areas_normalized_value'), ['normalized_value'], unique=False)

    op.create_table('firm_source_record_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('firm_source_record_id', sa.Integer(), nullable=False),
    sa.Column('link_method', sa.String(length=16), nullable=False),
    sa.Column('match_decision_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_source_record_id'], ['firm_source_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_decision_id'], ['match_review_queue.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'firm_source_record_id', name='uq_firm_source_record_link')
    )
    with op.batch_alter_table('firm_source_record_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firm_source_record_links_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_source_record_links_firm_source_record_id'), ['firm_source_record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm_source_record_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firm_source_record_links_firm_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_firm_source_record_links_firm_id'))

    op.drop_table('firm_source_record_links')
    with op.batch_alter_table('unmatched_practice_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unmatched_practice_areas_normalized_value'))

    op.drop_table('unmatched_practice_areas')
    with op.batch_alter_table('practice_area_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_area_aliases_practice_area_id'))
        batch_op.drop_index(batch_op.f('ix_practice_area_aliases_alias_normalized'))

    op.drop_table('practice_area_aliases')
    with op.batch_alter_table('offices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offices_state'))
        batch_op.drop_index(batch_op.f('ix_offices_phone_normalized'))
        batch_op.drop_index(batch_op.f('ix_offices_firm_id'))

    op.drop_table('offices')
    with op.batch_alter_table('match_review_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_review_queue_source_record_b_id'))
        batch_op.drop_index(batch_op.f('ix_match_review_queue_source_record_a_id'))

    op.drop_table('match_review_queue')
    with op.batch_alter_table('firm_practice_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firm_practice_areas_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_firm_practice_areas_practice_area_id'))
        batch_op.drop_index(batch_op.f('ix_firm_practice_areas_firm_id'))

    op.drop_table('firm_practice_areas')
    with op.batch_alter_table('firm_persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firm_persons_person_id'))
        batch_op.drop_index(batch_op.f('ix_firm_persons_firm_id'))

    op.drop_table('firm_persons')
    with op.batch_alter_table('practice_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_areas_slug'))
        batch_op.drop_index(batch_op.f('ix_practice_areas_parent_id'))

    op.drop_table('practice_areas')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persons_phone_normalized'))
        batch_op.drop_index(batch_op.f('ix_persons_last_name'))
        batch_op.drop_index(batch_op.f('ix_persons_email'))
        batch_op.drop_index(batch_op.f('ix_persons_bar_state'))

    op.drop_table('persons')
    with op.batch_alter_table('firms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firms_website_normalized'))
        batch_op.drop_index(batch_op.f('ix_firms_phone_normalized'))
        batch_op.drop_index(batch_op.f('ix_firms_name_normalized'))

    op.drop_table('firms')
    with op.batch_alter_table('firm_source_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firm_source_records_website_normalized'))
        batch_op.drop_index(batch_op.f('ix_firm_source_records_source'))
        batch_op.drop_index(batch_op.f('ix_firm_source_records_phone_normalized'))
        batch_op.drop_index(batch_op.f('ix_firm_source_records_name_normalized'))

    op.drop_table('firm_source_records')
    # ### end Alembic commands ###
