"""firm_source_record deactivation_status

Revision ID: 19964590cb93
Revises: 92ce585b2d96
Create Date: 2026-05-29 20:26:11.158331+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19964590cb93'
down_revision: Union[str, None] = '92ce585b2d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm_source_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deactivation_status', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_firm_source_records_deactivation_status'), ['deactivation_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm_source_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firm_source_records_deactivation_status'))
        batch_op.drop_column('deactivation_status')

    # ### end Alembic commands ###
