"""firm profile enrichment columns

Revision ID: 65f2655edbf2
Revises: e4774ab1701b
Create Date: 2026-06-01 16:27:10.384649+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f2655edbf2'
down_revision: Union[str, None] = 'e4774ab1701b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm_source_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_city', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('primary_state', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('primary_postal_code', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('office_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_subscriber', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('firm_short_description', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('firm_descriptions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('enrichment_status', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_firm_source_records_enrichment_status'), ['enrichment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_source_records_is_subscriber'), ['is_subscriber'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_source_records_primary_city'), ['primary_city'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_source_records_primary_state'), ['primary_state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm_source_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firm_source_records_primary_state'))
        batch_op.drop_index(batch_op.f('ix_firm_source_records_primary_city'))
        batch_op.drop_index(batch_op.f('ix_firm_source_records_is_subscriber'))
        batch_op.drop_index(batch_op.f('ix_firm_source_records_enrichment_status'))
        batch_op.drop_column('enrichment_status')
        batch_op.drop_column('firm_descriptions')
        batch_op.drop_column('firm_short_description')
        batch_op.drop_column('is_subscriber')
        batch_op.drop_column('office_count')
        batch_op.drop_column('primary_postal_code')
        batch_op.drop_column('primary_state')
        batch_op.drop_column('primary_city')

    # ### end Alembic commands ###
