"""website_enrichment table

Revision ID: 852fd3019b0b
Revises: 65f2655edbf2
Create Date: 2026-06-03 20:24:07.963023+00:00

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "852fd3019b0b"
down_revision: Union[str, None] = "65f2655edbf2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "website_enrichment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("website", sa.String(length=512), nullable=False),
        sa.Column("resolved_url", sa.String(length=1024), nullable=True),
        sa.Column("platform", sa.String(length=32), nullable=True),
        sa.Column("pages_crawled", sa.JSON(), nullable=True),
        sa.Column("is_law_related", sa.Boolean(), nullable=True),
        sa.Column("relevance_terms", sa.JSON(), nullable=True),
        sa.Column("attorney_count_min", sa.Integer(), nullable=True),
        sa.Column(
            "attorney_count_is_min", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("attorney_count_method", sa.String(length=24), nullable=True),
        sa.Column("attorney_count_confidence", sa.String(length=8), nullable=True),
        sa.Column("attorney_count_raw", sa.String(length=512), nullable=True),
        sa.Column("staff_count_min", sa.Integer(), nullable=True),
        sa.Column("office_count", sa.Integer(), nullable=True),
        sa.Column("office_addresses", sa.JSON(), nullable=True),
        sa.Column("years_in_operation_min", sa.Integer(), nullable=True),
        sa.Column("years_is_min", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=True),
        sa.Column("notable_signals", sa.JSON(), nullable=True),
        sa.Column("phones", sa.JSON(), nullable=True),
        sa.Column("description_blurb", sa.Text(), nullable=True),
        sa.Column("description_generated", sa.Text(), nullable=True),
        sa.Column("url_verification_status", sa.String(length=24), nullable=True),
        sa.Column("url_verification_score", sa.Float(), nullable=True),
        sa.Column("needs_render", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("raw_html_path", sa.String(length=1024), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("website_enrichment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_website_enrichment_enriched_at"), ["enriched_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_website_enrichment_needs_render"), ["needs_render"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_website_enrichment_url_verification_status"),
            ["url_verification_status"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_website_enrichment_website"), ["website"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("website_enrichment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_website_enrichment_website"))
        batch_op.drop_index(batch_op.f("ix_website_enrichment_url_verification_status"))
        batch_op.drop_index(batch_op.f("ix_website_enrichment_needs_render"))
        batch_op.drop_index(batch_op.f("ix_website_enrichment_enriched_at"))

    op.drop_table("website_enrichment")
    # ### end Alembic commands ###
