"""firm_persons primary contact + title rank

Revision ID: 92ce585b2d96
Revises: 0b231dde9c97
Create Date: 2026-05-28 18:57:07.876718+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ce585b2d96'
down_revision: Union[str, None] = '0b231dde9c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm_persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_primary_contact', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=False)
        batch_op.create_index('uq_firm_primary_contact', ['firm_id'], unique=True, sqlite_where=sa.text('is_primary_contact = 1'), postgresql_where=sa.text('is_primary_contact = true'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm_persons', schema=None) as batch_op:
        batch_op.drop_index('uq_firm_primary_contact', sqlite_where=sa.text('is_primary_contact = 1'), postgresql_where=sa.text('is_primary_contact = true'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_column('is_primary_contact')
        batch_op.drop_column('title_rank')

    # ### end Alembic commands ###
