"""drop uq_source_record_url

Revision ID: e4774ab1701b
Revises: 19964590cb93
Create Date: 2026-05-29 20:36:01.120329+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4774ab1701b'
down_revision: Union[str, None] = '19964590cb93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm_source_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_source_record_url'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm_source_records', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_source_record_url'), ['source', 'source_url'])

    # ### end Alembic commands ###
